postgreSQL:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: wallet_test
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 1
  maxRetries: 3
  poolSize: 10