swaggerServer:
  enable: true
  port: 1315

apiServer:
  enable: true
  port: 8082

postgreSQL:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  dbname: transaction
  sslmode: disable