swaggerServer:
  enable: true
  port: 1314
apiServer:  
  enable: true
  port: 8081
postgreSQL:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: wallet
  sslmode: disable