version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wallet_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: |
      postgres -c 'max_connections=200'
    networks:
      - wallet-network

  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CONFIG_FILE=config.yaml
    command: ["/bin/sh", "-c", "./main migrate --config config.yaml && ./main server --config config.yaml"]
    networks:
      - wallet-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  wallet-network:
    driver: bridge